name: Create release archive

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Archive Release
      uses: thedoctor0/zip-release@0.6.3
      with:
        type: 'zip'
        filename: 'CustomSuitLoader.zip'
        exclusions: '*.git* _*'
    - name: Upload Release
      uses: ncipollo/release-action@v1.12.0
      with:
        artifacts: "CustomSuitLoader.zip"
        token: ${{ secrets.GITHUB_TOKEN }}